### ISSUE TITLE
Next version PCB

### ISSUE THREAD

**Issue by traffael** [Octanis3/Octanis3-Electronics#12]
This issue summarizes the anticipated changes to the board for the next version.

+ larger MSP430 (e.g. FR5964) with maximum possible FRAM size for longer storage periods.
+ battery monitoring possibility (i.e. analog readout of the voltage)
- remove FI1 and replace with an alternative, less fragile filter part
- larger button

**Comment by traffael** [comment]
+ change IR receiver to something like this: TSOP75338WTR (TV remote IR receiver)

**Comment by deragent** [comment]
Design of v2 of Nestbox PCB is in progress (on branch Nestbox_v2). 

Will incorporate most of these changes proposed here.
